---
- name: Create user
  user:
    name: "{{ sudo_username }}"
    password: "{{ sudo_user_password }}"
    update_password: on_create
    home: "/home/'{{ sudo_username }}'"
    groups: sudo
    append: yes
    shell: /bin/bash
    state: present
    expires: -1
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_file: .ssh/id_rsa
    state: present

- name: Add SSH keys to sudo user
  copy:
    src: /root/.ssh/authorized_keys
    dest: /home/{{ sudo_username }}/.ssh/authorized_keys
    owner: "{{ sudo_username }}"
    group: "{{ sudo_username }}"
    mode: 0600
    #state: present

#- name: Add user to sudo group
  #shell: "adduser {{ sudo_username }} sudo"
